name: Validate packs & meals

on:
  push:
    paths: ["src/packs/**", "src/meals/**", "schemas/**", "scripts/validate.js", "package.json", "package-lock.json"]
  pull_request:
    paths: ["src/packs/**", "src/meals/**", "schemas/**", "scripts/validate.js", "package.json", "package-lock.json"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run validate